//! The provider translation core: configured providers in, canonical model
//! calls out, and their streams back in.
//!
//! **Where `llm-dialect` sits.** The crate is the canonical model and the
//! translation core between three client dialects — OpenAI chat/completions,
//! OpenAI Responses, and Anthropic Messages — and one internal shape. Its
//! dataflow is a *gateway's*: a client wire body is parsed into
//! [`ItemRequest`](llm_dialect::items::ItemRequest), flattened by
//! `dialect::deflate` into the OpenAI-chat-shaped
//! [`ChatRequest`](llm_dialect::canonical::ChatRequest) an engine consumes, and
//! the engine's responses are rendered back out to the client's dialect.
//!
//! vocoderd is not a gateway. It is a **client of providers**, so it needs the
//! three quadrants the crate does not have:
//!
//! | | wire → canonical | canonical → wire |
//! |---|---|---|
//! | **request** | crate (`*/req.rs`) | **here** (all three dialects) |
//! | **response** | **here** | crate (`*/out.rs`) |
//! | **stream** | **here** | crate (`*/stream.rs`) |
//!
//! The crate's halves are the client-facing ones; ours are their inverses. So
//! this module supplies the provider direction and *consumes* the crate's
//! canonical model, its `deflate`, and its validation — which is the part of
//! the crate that is not direction-specific and the reason it is a dependency
//! rather than a reimplementation. Where the crate does supply an adjacent
//! direction, its output is used as a **round-trip oracle** in the tests below:
//! SSE is generated by the crate's own framers and must decode back to the
//! chunks that produced it, which is a stronger check than any hand-written
//! fixture.
//!
//! One case is a pure win rather than an inversion: for an OpenAI
//! chat/completions provider, `deflate`'s output *is* the wire body, because
//! `ChatRequest` is defined as the engine's own shape. That dialect's request
//! builder is therefore a call into the crate plus the provider-only fields.
//!
//! **Purity.** Everything here is `serde_json::Value` in and out. No socket, no
//! runtime, no clock. The driver performs the call; see `provider_call.rs` for
//! the effect that carries it.

use llm_dialect::canonical::PREFILL_MARKER;
use llm_dialect::dialect::deflate::items_to_chat_request;
use llm_dialect::items::{ContentItem, ItemRequest, ItemStreamMessage, Role};
use serde_json::{Value, json};

use super::llm_replay::{BlockType, FinishReason, StreamChunk};

/// Which wire dialect a configured provider speaks.
///
/// The three the crate names, and the three vocoderd routes models to. A
/// provider entry that names an unknown dialect is refused at configuration
/// time rather than defaulted, because silently speaking the wrong protocol to
/// a live endpoint fails in a way that looks like a provider outage.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderKind {
    /// `POST {base}/chat/completions`, `data:`-framed SSE.
    OpenAiChat,
    /// `POST {base}/responses`, named `event:`/`data:` SSE.
    OpenAiResponses,
    /// `POST {base}/messages`, named `event:`/`data:` SSE.
    Anthropic,
}

impl ProviderKind {
    /// The dialect id as it appears in configuration and on the wire.
    #[cfg_attr(not(test), allow(dead_code))]
    pub fn id(self) -> &'static str {
        match self {
            Self::OpenAiChat => "openai-chat",
            Self::OpenAiResponses => "openai-responses",
            Self::Anthropic => "anthropic-messages",
        }
    }

    /// Parse a configured dialect id.
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "openai-chat" | "openai" | "chat-completions" => Some(Self::OpenAiChat),
            "openai-responses" | "responses" => Some(Self::OpenAiResponses),
            "anthropic-messages" | "anthropic" => Some(Self::Anthropic),
            _ => None,
        }
    }

    /// The path appended to a provider's base URL.
    pub fn path(self) -> &'static str {
        match self {
            Self::OpenAiChat => "chat/completions",
            Self::OpenAiResponses => "responses",
            Self::Anthropic => "messages",
        }
    }

    /// The auth header this dialect expects.
    ///
    /// Separate from the request body because the shape genuinely differs:
    /// Anthropic uses `x-api-key` while both OpenAI surfaces use
    /// `Authorization: Bearer`. Sending the wrong one is a 401, not a 400, so
    /// getting it wrong looks like a bad credential.
    fn auth_header(self) -> (&'static str, &'static str) {
        match self {
            Self::Anthropic => ("x-api-key", ""),
            _ => ("authorization", "Bearer "),
        }
    }
}

/// One configured provider route.
#[derive(Debug, Clone, PartialEq)]
pub struct ProviderConfig {
    /// The route id a model catalog's `provider` field refers to.
    pub id: String,
    pub kind: ProviderKind,
    /// Scheme + host + any base path, with no trailing slash.
    pub base_url: String,
    /// The model name to send, which is not always the catalog's display id.
    pub model: String,
    /// Name of the environment variable holding the key — a *name*, never the
    /// key itself, so a configuration dump cannot leak a credential.
    pub api_key_env: Option<String>,
}

impl ProviderConfig {
    /// The full URL this provider's calls go to.
    pub fn url(&self) -> String {
        format!(
            "{}/{}",
            self.base_url.trim_end_matches('/'),
            self.kind.path()
        )
    }

    /// Resolve the auth header pair, or `None` when no key is configured.
    ///
    /// The key is read from the environment here rather than stored, so it
    /// exists only for the duration of a call. An empty or unset variable is
    /// `None` — a provider with no key is legitimate (a local model server),
    /// and refusing the call belongs to whoever knows whether the endpoint
    /// needs one.
    pub fn auth(&self) -> Option<(String, String)> {
        let env = self.api_key_env.as_ref()?;
        let key = std::env::var(env).ok().filter(|k| !k.is_empty())?;
        let (name, prefix) = self.kind.auth_header();
        Some((name.to_string(), format!("{prefix}{key}")))
    }
}

/// Why a provider request could not be built.
#[derive(Debug, Clone, PartialEq)]
pub enum BuildError {
    /// The canonical request itself is malformed (the crate validates it).
    Invalid(String),
    /// The dialect cannot express something in the canonical request.
    ///
    /// A real case: Anthropic's wire *requires* `max_tokens`, and there is no
    /// value the translator may invent on the caller's behalf without silently
    /// clamping a request the caller meant to be unbounded.
    ///
    /// Unreachable today — `anthropic_body` supplies the dialect's own default
    /// rather than failing — but kept as a variant because the *category* is
    /// real and a caller must be able to branch on it once a dialect gains a
    /// field it genuinely cannot express.
    #[allow(dead_code)]
    Unsupported(String),
}

impl std::fmt::Display for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Invalid(m) => write!(f, "invalid request: {m}"),
            Self::Unsupported(m) => write!(f, "unsupported for this provider: {m}"),
        }
    }
}

impl std::error::Error for BuildError {}

/// Anthropic's documented fallback when a caller sets no cap.
///
/// The crate's `require_max_tokens` deliberately makes this the *caller's*
/// decision rather than the parser's; vocoderd is that caller, and it must pick
/// one number rather than let every request fail. 4096 is Anthropic's own
/// published default for `max_tokens`.
pub const ANTHROPIC_DEFAULT_MAX_TOKENS: u32 = 4096;

/// Build the wire body for one provider call.
///
/// `stream` is forced on: every path through this module consumes an SSE
/// response, so a provider that answered non-streamed would be asking the
/// decoder to handle a body it never produces. The session log's recorded
/// calls are streams, and so is the replay provider they are derived from.
pub fn to_wire_request(
    kind: ProviderKind,
    config: &ProviderConfig,
    items: &ItemRequest,
) -> Result<Value, BuildError> {
    items.validate().map_err(BuildError::Invalid)?;
    match kind {
        ProviderKind::OpenAiChat => openai_chat_body(config, items),
        ProviderKind::Anthropic => anthropic_body(config, items),
        ProviderKind::OpenAiResponses => responses_body(config, items),
    }
}

/// OpenAI chat/completions: `deflate`'s output is already this wire shape.
///
/// The crate defines `ChatRequest` as the engine's (i.e. OpenAI chat's) shape,
/// so the only work here is serializing it and applying the two
/// provider-only differences: the model actually configured for this route
/// (which may differ from what the client asked for), and stripping the
/// `_prefill` marker, which names an intent for an engine-side sender and
/// "must never reach an upstream" per the crate's own contract.
fn openai_chat_body(config: &ProviderConfig, items: &ItemRequest) -> Result<Value, BuildError> {
    let chat = items_to_chat_request(items).map_err(|e| BuildError::Invalid(e.to_string()))?;
    let mut body = serde_json::to_value(&chat)
        .map_err(|e| BuildError::Invalid(format!("serialize chat request: {e}")))?;
    let Some(obj) = body.as_object_mut() else {
        return Err(BuildError::Invalid("chat request was not an object".into()));
    };
    obj.remove(PREFILL_MARKER);
    obj.insert("model".into(), json!(config.model));
    obj.insert("stream".into(), json!(true));
    // Ask for the usage trailer. Without it the stream carries no token counts
    // and a recorded `assistant/message` would have no `usage` to replay.
    obj.insert("stream_options".into(), json!({ "include_usage": true }));
    Ok(body)
}

/// Render one canonical message's items as Anthropic content blocks.
fn anthropic_blocks(msg: &ItemStreamMessage) -> Vec<Value> {
    let mut out = Vec::new();
    for item in &msg.items {
        match item {
            ContentItem::Text { text } => out.push(json!({ "type": "text", "text": text })),
            // Ancestors of an assistant turn: `thinking` / `redacted_thinking`
            // must lead the block list, and `signature` is opaque — it is
            // re-emitted verbatim or the block is sent unsigned, never invented.
            ContentItem::Thinking {
                text,
                signature,
                redacted_data,
                ..
            } => {
                if let Some(data) = redacted_data {
                    out.push(json!({ "type": "redacted_thinking", "data": data }));
                } else if let Some(sig) = signature {
                    out.push(json!({
                        "type": "thinking", "thinking": text, "signature": sig,
                    }));
                } else {
                    // Unsigned thinking has no Anthropic wire form. Dropping it
                    // is what the crate's own deflate does for this case, and
                    // fabricating a signature would be rejected upstream.
                }
            }
            ContentItem::ToolCall {
                id,
                name,
                arguments,
            } => out.push(json!({
                "type": "tool_use", "id": id, "name": name, "input": arguments,
            })),
            ContentItem::ToolResult {
                tool_call_id,
                content,
                is_error,
            } => out.push(json!({
                "type": "tool_result",
                "tool_use_id": tool_call_id,
                "content": content,
                "is_error": is_error,
            })),
            ContentItem::Refusal { text } => out.push(json!({ "type": "text", "text": text })),
        }
    }
    out
}

/// Anthropic Messages: the inversion the crate does not supply.
///
/// `from_anthropic` parses this shape *into* canonical; nothing renders
/// canonical back out to it, because a gateway in front of an Anthropic backend
/// never needs to. Three details are Anthropic-specific and easy to get wrong:
/// the system prompt is a top-level field rather than a message, `max_tokens`
/// is required, and content blocks are typed rather than a role/content pair.
fn anthropic_body(config: &ProviderConfig, items: &ItemRequest) -> Result<Value, BuildError> {
    // System turns are hoisted out; Anthropic has no `system` role in
    // `messages` and rejects one. The crate's parser joins system blocks with
    // newlines, so this reverses that join.
    let system: String = items
        .messages
        .iter()
        .filter(|m| m.role == Role::System)
        .flat_map(|m| {
            m.items.iter().filter_map(|i| match i {
                ContentItem::Text { text } => Some(text.as_str()),
                _ => None,
            })
        })
        .collect::<Vec<_>>()
        .join("\n");

    let mut messages = Vec::new();
    for msg in &items.messages {
        if msg.role == Role::System {
            continue;
        }
        let role = match msg.role {
            Role::Assistant => "assistant",
            // Tool results ride inside a user turn on this dialect, which is
            // why no `tool` role appears here.
            Role::User | Role::Tool => "user",
            Role::System => unreachable!("filtered above"),
        };
        let content = anthropic_blocks(msg);
        if content.is_empty() {
            continue;
        }
        messages.push(json!({ "role": role, "content": content }));
    }

    let mut body = json!({
        "model": config.model,
        "messages": messages,
        "stream": true,
        "max_tokens": items.max_tokens.unwrap_or(ANTHROPIC_DEFAULT_MAX_TOKENS),
    });
    let obj = body
        .as_object_mut()
        .expect("body is an object by construction");
    if !system.is_empty() {
        obj.insert("system".into(), json!(system));
    }
    if let Some(t) = items.temperature {
        obj.insert("temperature".into(), json!(t));
    }
    if let Some(p) = items.top_p {
        obj.insert("top_p".into(), json!(p));
    }
    if let Some(stops) = &items.stop_sequences {
        obj.insert("stop_sequences".into(), json!(stops));
    }
    if !items.tools.is_empty() {
        let tools: Vec<Value> = items
            .tools
            .iter()
            .map(|t| {
                let mut v = json!({ "name": t.name, "input_schema": t.input_schema });
                if let Some(d) = &t.description {
                    v["description"] = json!(d);
                }
                v
            })
            .collect();
        obj.insert("tools".into(), json!(tools));
    }
    if let Some(choice) = &items.tool_choice {
        use llm_dialect::items::ToolChoice;
        let wire = match choice {
            ToolChoice::Auto => json!({ "type": "auto" }),
            ToolChoice::None => json!({ "type": "none" }),
            // Anthropic spells "any tool" as `any`, not `required`.
            ToolChoice::Required => json!({ "type": "any" }),
            ToolChoice::Tool { name } => json!({ "type": "tool", "name": name }),
        };
        obj.insert("tool_choice".into(), wire);
    }
    if let Some(th) = &items.thinking
        && let Some(budget) = th.budget_tokens
    {
        obj.insert(
            "thinking".into(),
            json!({ "type": "enabled", "budget_tokens": budget }),
        );
    }
    Ok(body)
}

/// OpenAI Responses: likewise an inversion, and the least symmetric of the
/// three.
///
/// The shape is not chat-shaped: a top-level `instructions` string replaces the
/// system turn, and the conversation is a flat list of typed input items where
/// an assistant tool call and its result are *separate items* rather than parts
/// of a message. Getting that flattening wrong is what makes a resumed
/// tool-calling turn 400.
fn responses_body(config: &ProviderConfig, items: &ItemRequest) -> Result<Value, BuildError> {
    let instructions: String = items
        .messages
        .iter()
        .filter(|m| m.role == Role::System)
        .flat_map(|m| {
            m.items.iter().filter_map(|i| match i {
                ContentItem::Text { text } => Some(text.as_str()),
                _ => None,
            })
        })
        .collect::<Vec<_>>()
        .join("\n");

    let mut input: Vec<Value> = Vec::new();
    for msg in &items.messages {
        if msg.role == Role::System {
            continue;
        }
        for item in &msg.items {
            match item {
                ContentItem::Text { text } => input.push(json!({
                    "role": match msg.role {
                        Role::Assistant => "assistant",
                        _ => "user",
                    },
                    "content": text,
                })),
                ContentItem::Thinking { .. } => {
                    // Reasoning items are replayed only with their encrypted
                    // payload, which the canonical model carries separately;
                    // unsigned reasoning is not a Responses input item.
                }
                ContentItem::ToolCall {
                    id,
                    name,
                    arguments,
                } => input.push(json!({
                    "type": "function_call",
                    "call_id": id,
                    "name": name,
                    // The Responses wire carries arguments as a JSON *string*.
                    "arguments": serde_json::to_string(arguments).unwrap_or_else(|_| "{}".into()),
                })),
                ContentItem::ToolResult {
                    tool_call_id,
                    content,
                    ..
                } => input.push(json!({
                    "type": "function_call_output",
                    "call_id": tool_call_id,
                    "output": match content {
                        Value::String(s) => s.clone(),
                        other => other.to_string(),
                    },
                })),
                ContentItem::Refusal { text } => input.push(json!({
                    "role": "assistant",
                    "content": text,
                })),
            }
        }
    }

    let mut body = json!({
        "model": config.model,
        "input": input,
        "stream": true,
    });
    let obj = body
        .as_object_mut()
        .expect("body is an object by construction");
    if !instructions.is_empty() {
        obj.insert("instructions".into(), json!(instructions));
    }
    if let Some(mt) = items.max_tokens {
        obj.insert("max_output_tokens".into(), json!(mt));
    }
    if let Some(t) = items.temperature {
        obj.insert("temperature".into(), json!(t));
    }
    if let Some(p) = items.top_p {
        obj.insert("top_p".into(), json!(p));
    }
    if !items.tools.is_empty() {
        let tools: Vec<Value> = items
            .tools
            .iter()
            .map(|t| {
                let mut v = json!({
                    "type": "function", "name": t.name, "parameters": t.input_schema,
                });
                if let Some(d) = &t.description {
                    v["description"] = json!(d);
                }
                v
            })
            .collect();
        obj.insert("tools".into(), json!(tools));
    }
    Ok(body)
}

// ---------------------------------------------------------------------------
// Inbound: server-sent events.
// ---------------------------------------------------------------------------

/// One decoded SSE frame.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SseFrame {
    /// The `event:` field, when the dialect names its events.
    pub event: Option<String>,
    /// The concatenated `data:` lines, per the SSE spec (multiple `data:`
    /// lines in one frame join with `\n`).
    pub data: String,
}

/// A pure incremental SSE decoder.
///
/// The crate has no inbound parser — its `dialect::sse` is the outbound pump
/// that builds an axum `Response`, and its declared `eventsource-stream`
/// dependency is unused — so this is ours. It is a state machine over bytes
/// rather than a line splitter because a network read boundary falls wherever
/// it likes, including mid-frame and mid-UTF-8-character; carrying the partial
/// frame across calls is what makes that a non-event.
///
/// Spec details that matter in practice: `data:` values have exactly one
/// leading space stripped (not trimmed), a frame is dispatched on a blank line,
/// comment lines (`:`) are ignored, and a field with no colon has an empty
/// value. `retry:`/`id:` are parsed and discarded — this client reconnects on
/// the caller's terms, not the server's.
#[derive(Debug, Default)]
pub struct SseDecoder {
    /// Bytes of the frame being assembled, decoded as UTF-8 only once the
    /// frame is complete — a multi-byte character can straddle two reads.
    buf: Vec<u8>,
    event: Option<String>,
    data: Vec<String>,
    /// The last `data:` byte ended with a newline, which the SSE spec strips
    /// from the joined value along with the final line's.
    data_newline: bool,
}

impl SseDecoder {
    pub fn new() -> Self {
        Self::default()
    }

    /// Feed bytes, appending every complete frame to `out`.
    pub fn feed(&mut self, bytes: &[u8], out: &mut Vec<SseFrame>) {
        self.buf.extend_from_slice(bytes);
        // Consume whole lines. A trailing partial line stays in the buffer
        // until its terminator arrives, which is the whole point of buffering.
        while let Some(nl) = self.buf.iter().position(|b| *b == b'\n') {
            let mut line: Vec<u8> = self.buf.drain(..=nl).collect();
            line.pop();
            // A CRLF terminator leaves the CR behind; strip it so values do
            // not accumulate a trailing control character.
            if line.last() == Some(&b'\r') {
                line.pop();
            }
            self.line(&line, out);
        }
    }

    /// Finish the stream, emitting any frame the server left unterminated.
    ///
    /// A provider that closes the connection without the final blank line has
    /// still sent its data, and discarding it would turn a complete response
    /// into a truncated one.
    pub fn finish(&mut self, out: &mut Vec<SseFrame>) {
        if !self.buf.is_empty() {
            let line = std::mem::take(&mut self.buf);
            let line = line.strip_suffix(b"\r").unwrap_or(&line).to_vec();
            self.line(&line, out);
        }
        self.dispatch(out);
    }

    fn line(&mut self, line: &[u8], out: &mut Vec<SseFrame>) {
        // Non-UTF-8 in a field name or value is not recoverable as text, but it
        // must not poison the rest of the stream: skip the line.
        let Ok(text) = std::str::from_utf8(line) else {
            return;
        };
        if text.is_empty() {
            self.dispatch(out);
            return;
        }
        // A comment (often a keep-alive `: ping`) carries no field.
        if text.starts_with(':') {
            return;
        }
        let (field, value) = match text.split_once(':') {
            Some((f, v)) => (f, v.strip_prefix(' ').unwrap_or(v)),
            None => (text, ""),
        };
        match field {
            "event" => self.event = Some(value.to_string()),
            "data" => {
                self.data.push(value.to_string());
                self.data_newline = true;
            }
            // `id` and `retry` are parsed and dropped: this client owns its
            // own reconnect policy and has no use for the server's hints.
            _ => {}
        }
    }

    fn dispatch(&mut self, out: &mut Vec<SseFrame>) {
        if self.data.is_empty() && self.event.is_none() {
            return;
        }
        // The spec strips the newline that terminated the last `data:` line,
        // having used it to join the others.
        let mut data = self.data.join("\n");
        if self.data_newline {
            data.push('\n');
        }
        let data = data.strip_suffix('\n').unwrap_or(&data).to_string();
        self.data.clear();
        self.data_newline = false;
        out.push(SseFrame {
            event: self.event.take(),
            data,
        });
    }
}

/// Map a provider's finish reason onto the seam's vocabulary.
///
/// The three dialects disagree on spelling for the same three outcomes, and
/// `length`/`max_tokens` must land on [`FinishReason::MaxTokens`] rather than
/// `Stop`: the FSM makes a turn's ending sticky on it, so a mis-mapped
/// truncation would report a truncated turn as a complete one.
fn finish_from_wire(kind: ProviderKind, raw: &str) -> Option<FinishReason> {
    Some(match (kind, raw) {
        (ProviderKind::OpenAiChat, "stop") => FinishReason::Stop,
        (ProviderKind::OpenAiChat, "tool_calls") => FinishReason::ToolCalls,
        (ProviderKind::OpenAiChat, "length") => FinishReason::MaxTokens,
        // A filtered response is a completed call with no usable content; the
        // seam has no separate vocabulary for it and inventing an error would
        // misreport a call the provider considers successful.
        (ProviderKind::OpenAiChat, "content_filter") => FinishReason::Stop,

        (ProviderKind::OpenAiResponses, "stop") => FinishReason::Stop,
        (ProviderKind::OpenAiResponses, "tool_calls") => FinishReason::ToolCalls,
        (ProviderKind::OpenAiResponses, "max_output_tokens") => FinishReason::MaxTokens,

        (ProviderKind::Anthropic, "end_turn") => FinishReason::Stop,
        (ProviderKind::Anthropic, "stop_sequence") => FinishReason::Stop,
        (ProviderKind::Anthropic, "tool_use") => FinishReason::ToolCalls,
        (ProviderKind::Anthropic, "max_tokens") => FinishReason::MaxTokens,
        (ProviderKind::Anthropic, "refusal") => FinishReason::Stop,
        _ => return None,
    })
}

/// Whether an SSE frame's `data` is a terminal sentinel rather than JSON.
fn is_done_sentinel(data: &str) -> bool {
    data.trim() == "[DONE]"
}

/// Whether a post-finish frame still carries usage worth keeping.
///
/// OpenAI chat's usage trailer is the one frame that legitimately follows the
/// terminal chunk; everything else after a finish is ignored.
fn carries_usage(value: &Value) -> bool {
    value.get("usage").is_some_and(|u| !u.is_null())
}

/// Decode a provider's SSE stream into the seam's chunks.
///
/// This is the inverse of the crate's per-dialect framers and the piece the
/// loop actually consumes. It is stateful across frames because block indices
/// do not exist on the OpenAI wire at all (they are invented here, in
/// appearance order) and because Anthropic's blocks *do* exist but arrive as
/// separate start/delta/stop events that must be joined into the seam's
/// `BlockStart`/deltas/`BlockEnd` shape.
#[derive(Debug, Default)]
pub struct ProviderStreamDecoder {
    kind: Option<ProviderKind>,
    /// Next block index to allocate, for dialects without one.
    next_index: u64,
    /// Whether a block is currently open, for the same reason.
    open: Option<(u64, BlockType)>,
    /// Which block index each tool call id was assigned.
    tool_index: std::collections::HashMap<String, u64>,
    /// Anthropic carries `message_start` usage before any content.
    input_tokens: Option<u64>,
    /// A finish reason seen but not yet emitted.
    ///
    /// OpenAI chat reports `finish_reason` on the last *delta* and the token
    /// counts in a **separate frame that follows it**. The seam's contract is
    /// that a stream ends with its finish chunk (`derive_replay_script` refuses
    /// one that does not), so the reason is held here and emitted after the
    /// usage trailer or at end of stream — the same deferral the crate
    /// documents for the Responses terminal frame.
    pending_finish: Option<FinishReason>,
    finished: bool,
}

impl ProviderStreamDecoder {
    pub fn new(kind: ProviderKind) -> Self {
        Self {
            kind: Some(kind),
            ..Default::default()
        }
    }

    /// Flush a deferred finish reason.
    ///
    /// Must be called once no more frames can arrive — on `[DONE]` or at
    /// stream end. A stream that produced content but no terminal frame is left
    /// without one on purpose: inventing a `Stop` here would make a truncated
    /// call replay as a complete one, which is the failure
    /// `derive_replay_script` exists to refuse.
    pub fn end(&mut self, out: &mut Vec<StreamChunk>) {
        self.close_open(out);
        if let Some(reason) = self.pending_finish.take() {
            self.finished = true;
            out.push(StreamChunk::Finish { reason });
        }
    }

    /// Close any block left open by a stream that ended without its stop
    /// event, or by a dialect that never sends one.
    ///
    /// Providers do this on an upstream error mid-block. Leaving the block open
    /// would hand the assembler a response whose last block never closed, and
    /// the recorded row would replay differently from how it was produced.
    ///
    /// The block is emitted **empty on purpose**. This decoder's job is the
    /// chunk vocabulary; assembling a block's accumulated value belongs to
    /// whoever consumes the chunks, and doing it here as well would mean two
    /// places could disagree about what a block contains. The one exception is
    /// a tool call, whose arguments are the concatenated fragments and nothing
    /// else — but that too is read off the deltas by the consumer, so it stays
    /// out of here.
    fn close_open(&mut self, out: &mut Vec<StreamChunk>) {
        if let Some((index, block_type)) = self.open.take() {
            let block = match block_type {
                BlockType::Text => json!({ "type": "text", "text": "" }),
                BlockType::Reasoning => json!({ "type": "reasoning", "text": "" }),
                BlockType::ToolCall => json!({ "type": "tool-call" }),
            };
            out.push(StreamChunk::BlockEnd { index, block });
        }
    }

    /// Ensure a block of `block_type` is open, closing a different one first.
    fn ensure_open(&mut self, block_type: BlockType, out: &mut Vec<StreamChunk>) -> u64 {
        if let Some((index, open_type)) = self.open
            && open_type == block_type
        {
            return index;
        }
        self.close_open(out);
        let index = self.next_index;
        self.next_index += 1;
        self.open = Some((index, block_type));
        out.push(StreamChunk::BlockStart { index, block_type });
        index
    }

    /// Decode one frame, appending any chunks it produced.
    pub fn frame(&mut self, frame: &SseFrame, out: &mut Vec<StreamChunk>) {
        if is_done_sentinel(&frame.data) {
            self.end(out);
            return;
        }
        let Ok(value) = serde_json::from_str::<Value>(&frame.data) else {
            // A frame that is not JSON is not a chunk. Providers interleave
            // keep-alives and vendor extensions; skipping is correct, and
            // failing the whole stream on one would be wrong.
            return;
        };
        // Once a terminal chunk has been emitted only a usage trailer can still
        // add anything.
        if self.finished && !carries_usage(&value) {
            return;
        }
        let kind = self.kind.expect("kind set at construction");
        match kind {
            ProviderKind::OpenAiChat => self.openai_chat_frame(&value, out),
            ProviderKind::OpenAiResponses => {
                self.responses_frame(frame.event.as_deref(), &value, out)
            }
            ProviderKind::Anthropic => self.anthropic_frame(&value, out),
        }
    }

    /// Chat/completions deltas: one flat `choices[0].delta` per frame.
    fn openai_chat_frame(&mut self, value: &Value, out: &mut Vec<StreamChunk>) {
        // The usage trailer arrives with an empty `choices`, so usage is read
        // before the choice is required.
        if let Some(usage) = value.get("usage").filter(|u| !u.is_null()) {
            out.push(StreamChunk::Usage {
                usage: normalize_usage(ProviderKind::OpenAiChat, usage),
            });
        }
        let Some(choice) = value.get("choices").and_then(|c| c.get(0)) else {
            return;
        };
        if let Some(delta) = choice.get("delta") {
            // Reasoning arrives in one of two shapes on this surface, and both
            // are real:
            //
            // - `reasoning_content` (vLLM/DeepSeek) or `reasoning`, a plain
            //   string on the delta;
            // - a nested `thinking: {block_index, kind, text}` object, which is
            //   what an Anthropic backend fronted by a chat-completions surface
            //   emits — and, not coincidentally, the exact shape this crate's
            //   own `AnthropicFramer` produces. Verified against a live gateway
            //   rather than assumed: it sends `thinking` and no
            //   `reasoning_content` at all.
            //
            // Reading only the first shape would silently drop every reasoning
            // token from such a provider, which is invisible in the transcript
            // (the visible text is unaffected) and wrong in the log.
            let reasoning = delta
                .get("reasoning_content")
                .or_else(|| delta.get("reasoning"))
                .and_then(Value::as_str)
                .map(str::to_string)
                .or_else(|| {
                    delta
                        .get("thinking")
                        .and_then(|t| t.get("text"))
                        .and_then(Value::as_str)
                        .map(str::to_string)
                });
            if let Some(text) = reasoning.filter(|t| !t.is_empty()) {
                let index = self.ensure_open(BlockType::Reasoning, out);
                out.push(StreamChunk::ReasoningDelta { index, text });
            }
            if let Some(text) = delta.get("content").and_then(Value::as_str)
                && !text.is_empty()
            {
                let index = self.ensure_open(BlockType::Text, out);
                out.push(StreamChunk::TextDelta {
                    index,
                    text: text.to_string(),
                });
            }
            if let Some(calls) = delta.get("tool_calls").and_then(Value::as_array) {
                for call in calls {
                    self.openai_tool_delta(call, out);
                }
            }
        }
        if let Some(reason) = choice.get("finish_reason").and_then(Value::as_str) {
            self.close_open(out);
            if let Some(finish) = finish_from_wire(ProviderKind::OpenAiChat, reason) {
                // Deferred, not emitted: this frame is followed by the usage
                // trailer, and the seam's contract is that a stream *ends* with
                // its finish chunk.
                self.pending_finish = Some(finish);
            }
        }
    }

    fn openai_tool_delta(&mut self, call: &Value, out: &mut Vec<StreamChunk>) {
        // Chat tool deltas carry a wire `index` that is authoritative and
        // distinct from the block index; the id may arrive only on the first
        // delta for that call.
        let wire_index = call.get("index").and_then(Value::as_u64).unwrap_or(0);
        let id = call
            .get("id")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string();
        let name = call
            .pointer("/function/name")
            .and_then(Value::as_str)
            .map(str::to_string);
        let args = call
            .pointer("/function/arguments")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string();

        // The block index is allocated per tool call and remembered, because
        // later deltas for the same call frequently omit both `id` and `index`
        // and would otherwise open a fresh block per fragment.
        let key = if id.is_empty() {
            format!("idx:{wire_index}")
        } else {
            id.clone()
        };
        let index = match self.tool_index.get(&key) {
            Some(index) => *index,
            None => {
                let index = self.ensure_open(BlockType::ToolCall, out);
                self.tool_index.insert(key, index);
                index
            }
        };
        if name.is_some() || !args.is_empty() || !id.is_empty() {
            out.push(StreamChunk::ToolCallDelta {
                index,
                id,
                name,
                arguments_delta: args,
            });
        }
    }

    /// Responses events, dispatched on the `event:` name with the payload's
    /// own `type` as a cross-check.
    fn responses_frame(&mut self, event: Option<&str>, value: &Value, out: &mut Vec<StreamChunk>) {
        let ty = value
            .get("type")
            .and_then(Value::as_str)
            .or(event)
            .unwrap_or_default();
        match ty {
            "response.output_text.delta" => {
                if let Some(text) = value.get("delta").and_then(Value::as_str) {
                    let index = self.ensure_open(BlockType::Text, out);
                    out.push(StreamChunk::TextDelta {
                        index,
                        text: text.to_string(),
                    });
                }
            }
            "response.reasoning_summary_text.delta" | "response.reasoning_text.delta" => {
                if let Some(text) = value.get("delta").and_then(Value::as_str) {
                    let index = self.ensure_open(BlockType::Reasoning, out);
                    out.push(StreamChunk::ReasoningDelta {
                        index,
                        text: text.to_string(),
                    });
                }
            }
            "response.output_item.added" => {
                if let Some(item) = value.get("item")
                    && item.get("type").and_then(Value::as_str) == Some("function_call")
                {
                    let key = item
                        .get("call_id")
                        .and_then(Value::as_str)
                        .or_else(|| item.get("id").and_then(Value::as_str))
                        .unwrap_or_default()
                        .to_string();
                    let index = self.ensure_open(BlockType::ToolCall, out);
                    self.tool_index.insert(key, index);
                    out.push(StreamChunk::ToolCallDelta {
                        index,
                        id: item
                            .get("call_id")
                            .and_then(Value::as_str)
                            .unwrap_or_default()
                            .to_string(),
                        name: item.get("name").and_then(Value::as_str).map(str::to_string),
                        arguments_delta: String::new(),
                    });
                }
            }
            "response.function_call_arguments.delta" => {
                if let Some(text) = value.get("delta").and_then(Value::as_str) {
                    // The delta names only the item; recover the block by the
                    // call id it was opened under.
                    let key = value
                        .get("call_id")
                        .or_else(|| value.get("item_id"))
                        .and_then(Value::as_str)
                        .unwrap_or_default()
                        .to_string();
                    let index = self
                        .tool_index
                        .get(&key)
                        .copied()
                        .unwrap_or_else(|| self.ensure_open(BlockType::ToolCall, out));
                    out.push(StreamChunk::ToolCallDelta {
                        index,
                        id: key,
                        name: None,
                        arguments_delta: text.to_string(),
                    });
                }
            }
            "response.completed" | "response.incomplete" | "response.failed" => {
                let response = value.get("response").unwrap_or(value);
                if let Some(usage) = response.get("usage").filter(|u| !u.is_null()) {
                    out.push(StreamChunk::Usage {
                        usage: normalize_usage(ProviderKind::OpenAiResponses, usage),
                    });
                }
                self.close_open(out);
                let reason = match ty {
                    "response.completed" => {
                        // A completed response that emitted a function call is
                        // a tool-calls turn even though the status spells
                        // "completed".
                        if self.tool_index.is_empty() {
                            FinishReason::Stop
                        } else {
                            FinishReason::ToolCalls
                        }
                    }
                    // `incomplete` is only ever a truncation on this surface:
                    // the other cause, a content filter, surfaces as `failed`.
                    "response.incomplete" => FinishReason::MaxTokens,
                    _ => {
                        let message = response
                            .get("error")
                            .and_then(|e| e.get("message"))
                            .and_then(Value::as_str)
                            .unwrap_or("provider reported a failed response")
                            .to_string();
                        let code = response
                            .get("error")
                            .and_then(|e| e.get("code"))
                            .and_then(Value::as_str)
                            .unwrap_or("RESPONSE_FAILED")
                            .to_string();
                        FinishReason::Error { message, code }
                    }
                };
                self.finished = true;
                out.push(StreamChunk::Finish { reason });
            }
            _ => {}
        }
    }

    /// Anthropic's event stream: explicit blocks, so `content_block_*` maps
    /// one-to-one onto the seam's block vocabulary.
    fn anthropic_frame(&mut self, value: &Value, out: &mut Vec<StreamChunk>) {
        let ty = value
            .get("type")
            .and_then(Value::as_str)
            .unwrap_or_default();
        let index = value.get("index").and_then(Value::as_u64).unwrap_or(0);
        match ty {
            "message_start" => {
                // Anthropic reports input tokens once, up front, before any
                // content — so it cannot ride the trailing usage chunk alone.
                if let Some(n) = value
                    .pointer("/message/usage/input_tokens")
                    .and_then(Value::as_u64)
                {
                    self.input_tokens = Some(n);
                }
            }
            "content_block_start" => {
                let block = value.get("content_block").unwrap_or(&Value::Null);
                let block_type = match block.get("type").and_then(Value::as_str) {
                    Some("text") => BlockType::Text,
                    Some("thinking") | Some("redacted_thinking") => BlockType::Reasoning,
                    Some("tool_use") => BlockType::ToolCall,
                    // An unknown block type is skipped rather than guessed: a
                    // future block would otherwise be mistranslated into a
                    // wrong one and silently corrupt the recorded stream.
                    _ => return,
                };
                self.close_open(out);
                self.open = Some((index, block_type));
                self.next_index = self.next_index.max(index + 1);
                out.push(StreamChunk::BlockStart { index, block_type });
                // A tool_use block announces its id and name here, and the
                // fragments start empty.
                if block_type == BlockType::ToolCall {
                    let id = block
                        .get("id")
                        .and_then(Value::as_str)
                        .unwrap_or_default()
                        .to_string();
                    self.tool_index.insert(id.clone(), index);
                    out.push(StreamChunk::ToolCallDelta {
                        index,
                        id,
                        name: block
                            .get("name")
                            .and_then(Value::as_str)
                            .map(str::to_string),
                        arguments_delta: String::new(),
                    });
                }
            }
            "content_block_delta" => {
                let delta = value.get("delta").unwrap_or(&Value::Null);
                match delta.get("type").and_then(Value::as_str) {
                    Some("text_delta") => {
                        if let Some(text) = delta.get("text").and_then(Value::as_str) {
                            out.push(StreamChunk::TextDelta {
                                index,
                                text: text.to_string(),
                            });
                        }
                    }
                    Some("thinking_delta") => {
                        if let Some(text) = delta.get("thinking").and_then(Value::as_str) {
                            out.push(StreamChunk::ReasoningDelta {
                                index,
                                text: text.to_string(),
                            });
                        }
                    }
                    Some("input_json_delta") => {
                        if let Some(text) = delta.get("partial_json").and_then(Value::as_str) {
                            out.push(StreamChunk::ToolCallDelta {
                                index,
                                id: String::new(),
                                name: None,
                                arguments_delta: text.to_string(),
                            });
                        }
                    }
                    // `signature_delta` carries the opaque thinking signature,
                    // which the seam's chunk vocabulary has no field for; the
                    // assembled block's signature arrives on `content_block_stop`.
                    _ => {}
                }
            }
            "content_block_stop" => {
                self.close_open(out);
            }
            "message_delta" => {
                if let Some(usage) = value.get("usage") {
                    let mut usage = normalize_usage(ProviderKind::Anthropic, usage);
                    // Anthropic reports input tokens at `message_start`; the
                    // trailing delta carries only output. Folding them here is
                    // what makes the usage chunk complete on this surface.
                    if let Some(n) = self.input_tokens
                        && usage.get("inputTokens").and_then(Value::as_u64) == Some(0)
                    {
                        usage["inputTokens"] = json!(n);
                    }
                    out.push(StreamChunk::Usage { usage });
                }
                if let Some(reason) = value.pointer("/delta/stop_reason").and_then(Value::as_str) {
                    self.close_open(out);
                    if let Some(finish) = finish_from_wire(ProviderKind::Anthropic, reason) {
                        self.finished = true;
                        out.push(StreamChunk::Finish { reason: finish });
                    }
                }
            }
            "error" => {
                self.close_open(out);
                let message = value
                    .pointer("/error/message")
                    .and_then(Value::as_str)
                    .unwrap_or("provider reported an error")
                    .to_string();
                let code = value
                    .pointer("/error/type")
                    .and_then(Value::as_str)
                    .unwrap_or("PROVIDER_ERROR")
                    .to_uppercase();
                self.finished = true;
                out.push(StreamChunk::Finish {
                    reason: FinishReason::Error { message, code },
                });
            }
            _ => {}
        }
    }
}

/// Rewrite a provider's usage object into the seam's `inputTokens` /
/// `outputTokens` vocabulary.
///
/// The three dialects disagree on both naming and, on Anthropic, on
/// **semantics**: Anthropic's `input_tokens` excludes cached tokens while the
/// other two include them. A cached turn therefore reports fewer fresh input
/// tokens on Anthropic for the same work, and normalizing to the inclusive
/// convention is what makes a recorded turn's cost comparable across
/// providers — the same rule the crate states as a cross-dialect invariant.
fn normalize_usage(kind: ProviderKind, usage: &Value) -> Value {
    let u64_at = |v: &Value, keys: &[&str]| -> u64 {
        keys.iter()
            .find_map(|k| v.get(*k).and_then(Value::as_u64))
            .unwrap_or(0)
    };
    match kind {
        ProviderKind::OpenAiChat => json!({
            "inputTokens": u64_at(usage, &["prompt_tokens"]),
            "outputTokens": u64_at(usage, &["completion_tokens"]),
        }),
        ProviderKind::OpenAiResponses => json!({
            "inputTokens": u64_at(usage, &["input_tokens"]),
            "outputTokens": u64_at(usage, &["output_tokens"]),
        }),
        ProviderKind::Anthropic => {
            let fresh = u64_at(usage, &["input_tokens"]);
            let cache_read = u64_at(usage, &["cache_read_input_tokens"]);
            let cache_write = u64_at(usage, &["cache_creation_input_tokens"]);
            json!({
                "inputTokens": fresh + cache_read + cache_write,
                "outputTokens": u64_at(usage, &["output_tokens"]),
            })
        }
    }
}

/// Decode a complete SSE body into chunks, for a non-incremental caller.
///
/// The tests' entry point: the driver decodes incrementally through
/// [`SseDecoder`] and [`ProviderStreamDecoder`] directly.
#[cfg_attr(not(test), allow(dead_code))]
pub fn decode_stream(kind: ProviderKind, body: &str) -> Vec<StreamChunk> {
    let mut decoder = SseDecoder::new();
    let mut frames = Vec::new();
    decoder.feed(body.as_bytes(), &mut frames);
    decoder.finish(&mut frames);
    let mut stream = ProviderStreamDecoder::new(kind);
    let mut chunks = Vec::new();
    for frame in &frames {
        stream.frame(frame, &mut chunks);
    }
    // Flush a deferred finish reason: a provider that closed without `[DONE]`
    // still ended, and so does one whose last frame was the finish itself.
    stream.end(&mut chunks);
    chunks
}

#[cfg(test)]
mod tests {
    use super::*;
    use llm_dialect::dialect::anthropic::req::from_anthropic;
    use llm_dialect::dialect::openai_chat::req::from_openai_chat;
    use llm_dialect::dialect::openai_responses::req::from_openai_responses;

    fn config(kind: ProviderKind) -> ProviderConfig {
        ProviderConfig {
            id: "test".into(),
            kind,
            base_url: "https://api.example.com/v1".into(),
            model: "test-model".into(),
            api_key_env: Some("VOC_TEST_KEY_UNSET".into()),
        }
    }

    fn items_from(kind: ProviderKind, body: Value) -> ItemRequest {
        match kind {
            ProviderKind::OpenAiChat => from_openai_chat(&body).expect("parses"),
            ProviderKind::OpenAiResponses => from_openai_responses(&body).expect("parses"),
            ProviderKind::Anthropic => from_anthropic(&body).expect("parses"),
        }
    }

    /// The route's URL and auth header per dialect. Getting the header name
    /// wrong is a 401 that reads as a bad credential, so it is asserted rather
    /// than left to integration.
    #[test]
    fn each_dialect_uses_its_own_path_and_auth_header() {
        assert_eq!(
            config(ProviderKind::OpenAiChat).url(),
            "https://api.example.com/v1/chat/completions"
        );
        assert_eq!(
            config(ProviderKind::OpenAiResponses).url(),
            "https://api.example.com/v1/responses"
        );
        assert_eq!(
            config(ProviderKind::Anthropic).url(),
            "https://api.example.com/v1/messages"
        );
        // A trailing slash in configuration must not double up.
        let mut c = config(ProviderKind::Anthropic);
        c.base_url = "https://api.example.com/v1/".into();
        assert_eq!(c.url(), "https://api.example.com/v1/messages");
    }

    #[test]
    fn dialect_ids_round_trip_and_reject_the_unknown() {
        for kind in [
            ProviderKind::OpenAiChat,
            ProviderKind::OpenAiResponses,
            ProviderKind::Anthropic,
        ] {
            assert_eq!(ProviderKind::parse(kind.id()), Some(kind));
        }
        assert_eq!(ProviderKind::parse("gemini"), None);
    }

    /// The API key is read from the environment at call time and never stored,
    /// so a configuration dump cannot leak it.
    #[test]
    fn the_api_key_is_read_from_the_environment_not_the_config() {
        let mut c = config(ProviderKind::Anthropic);
        c.api_key_env = Some("VOC_TEST_KEY_ANTHROPIC_AUTH".into());
        // SAFETY: single-threaded test, and the variable is unique to it.
        unsafe { std::env::set_var("VOC_TEST_KEY_ANTHROPIC_AUTH", "sk-test") };
        let (name, value) = c.auth().expect("key present");
        assert_eq!(name, "x-api-key");
        assert_eq!(value, "sk-test");

        c.kind = ProviderKind::OpenAiChat;
        let (name, value) = c.auth().expect("key present");
        assert_eq!(name, "authorization");
        assert_eq!(value, "Bearer sk-test");
        unsafe { std::env::remove_var("VOC_TEST_KEY_ANTHROPIC_AUTH") };
    }

    /// An unset variable is "no key configured", not an empty credential: a
    /// local model server legitimately needs none.
    #[test]
    fn an_unset_key_variable_means_no_auth_rather_than_an_empty_one() {
        let mut c = config(ProviderKind::OpenAiChat);
        c.api_key_env = Some("VOC_TEST_KEY_DEFINITELY_UNSET".into());
        assert_eq!(c.auth(), None);
        c.api_key_env = None;
        assert_eq!(c.auth(), None);
    }

    /// The crate's `deflate` output *is* the chat/completions wire body, so
    /// this direction is a pass-through — plus the two provider-only fields.
    #[test]
    fn chat_completions_reuses_deflates_output_as_the_wire_body() {
        let items = items_from(
            ProviderKind::OpenAiChat,
            json!({"model":"m","messages":[{"role":"user","content":"hi"}]}),
        );
        let body = to_wire_request(
            ProviderKind::OpenAiChat,
            &config(ProviderKind::OpenAiChat),
            &items,
        )
        .expect("builds");
        assert_eq!(body["model"], "test-model", "the configured model wins");
        assert_eq!(body["stream"], true);
        assert_eq!(body["stream_options"]["include_usage"], true);
        assert_eq!(body["messages"][0]["content"], "hi");
    }

    /// The prefill marker names an intent for an engine-side sender and must
    /// never reach an upstream — the crate's own contract for it.
    #[test]
    fn the_prefill_marker_never_reaches_the_wire() {
        let items = items_from(
            ProviderKind::OpenAiChat,
            json!({
                "model": "m",
                "messages": [
                    {"role": "user", "content": "count"},
                    {"role": "assistant", "content": "1, 2"},
                ],
            }),
        );
        let body = to_wire_request(
            ProviderKind::OpenAiChat,
            &config(ProviderKind::OpenAiChat),
            &items,
        )
        .expect("builds");
        assert!(
            body.get(PREFILL_MARKER).is_none(),
            "marker leaked to the wire: {body}"
        );
    }

    /// **Round trip through the crate's own parser.** The Anthropic body this
    /// module renders must parse back into the canonical request it came from
    /// — the crate supplies the parse direction, so it is the oracle for the
    /// render direction this module supplies.
    #[test]
    fn an_anthropic_body_round_trips_through_the_crates_parser() {
        let original = items_from(
            ProviderKind::Anthropic,
            json!({
                "model": "ignored",
                "max_tokens": 256,
                "system": "be terse",
                "temperature": 0.25,
                "messages": [
                    {"role": "user", "content": "what is 2+2?"},
                    {"role": "assistant", "content": [
                        {"type": "text", "text": "four"},
                    ]},
                ],
                "tools": [{
                    "name": "lookup",
                    "description": "look something up",
                    "input_schema": {"type": "object", "properties": {}},
                }],
            }),
        );
        let body = to_wire_request(
            ProviderKind::Anthropic,
            &config(ProviderKind::Anthropic),
            &original,
        )
        .expect("builds");
        assert_eq!(body["model"], "test-model");
        assert_eq!(body["stream"], true);
        assert_eq!(body["max_tokens"], 256);
        assert_eq!(body["system"], "be terse");
        assert_eq!(body["temperature"], 0.25);
        assert_eq!(body["tools"][0]["name"], "lookup");

        let back = from_anthropic(&body).expect("our own body must parse");
        // The configured model replaces the catalog id on the wire, so the
        // round trip agrees on everything *except* the model — which is the
        // point of a provider route.
        assert_eq!(back.model, "test-model");
        assert_eq!(back.max_tokens, original.max_tokens);
        assert_eq!(back.temperature, original.temperature);
        assert_eq!(back.tools.len(), original.tools.len());
        assert_eq!(back.tools[0].name, original.tools[0].name);
        assert_eq!(back.messages.len(), original.messages.len());
        for (a, b) in back.messages.iter().zip(original.messages.iter()) {
            assert_eq!(a.role, b.role, "role preserved through the round trip");
        }
    }

    /// Anthropic requires `max_tokens`; a caller who set no cap gets the
    /// documented default rather than a request the provider rejects.
    #[test]
    fn anthropic_supplies_a_max_tokens_when_the_caller_set_none() {
        let items = items_from(
            ProviderKind::Anthropic,
            json!({"model":"m","max_tokens":10,"messages":[{"role":"user","content":"x"}]}),
        );
        // Drop the cap by rebuilding canonical without one.
        let mut items = items;
        items.max_tokens = None;
        let body = to_wire_request(
            ProviderKind::Anthropic,
            &config(ProviderKind::Anthropic),
            &items,
        )
        .expect("builds");
        assert_eq!(body["max_tokens"], ANTHROPIC_DEFAULT_MAX_TOKENS);
    }

    /// A tool result rides inside a user turn on Anthropic and as its own typed
    /// item on Responses — the two flattenings differ, and a resumed
    /// tool-calling turn is exactly where getting them wrong 400s.
    #[test]
    fn tool_results_flatten_per_dialect() {
        let items = items_from(
            ProviderKind::Anthropic,
            json!({
                "model": "m", "max_tokens": 64,
                "messages": [
                    {"role": "user", "content": "weather?"},
                    {"role": "assistant", "content": [
                        {"type": "tool_use", "id": "call_1", "name": "get_weather",
                         "input": {"city": "Paris"}},
                    ]},
                    {"role": "user", "content": [
                        {"type": "tool_result", "tool_use_id": "call_1", "content": "18C"},
                    ]},
                ],
            }),
        );
        assert_eq!(items.messages.len(), 3, "fixture must hold a tool result");

        let anthropic = to_wire_request(
            ProviderKind::Anthropic,
            &config(ProviderKind::Anthropic),
            &items,
        )
        .expect("builds");
        // The result is a content block inside a user message.
        assert_eq!(anthropic["messages"][2]["role"], "user");
        assert_eq!(
            anthropic["messages"][2]["content"][0]["type"],
            "tool_result"
        );
        assert_eq!(
            anthropic["messages"][2]["content"][0]["tool_use_id"],
            "call_1"
        );
        assert_eq!(anthropic["messages"][1]["content"][0]["type"], "tool_use");

        let responses = to_wire_request(
            ProviderKind::OpenAiResponses,
            &config(ProviderKind::OpenAiResponses),
            &items,
        )
        .expect("builds");
        // The same conversation is three flat typed items, not messages.
        let input = responses["input"].as_array().expect("input is an array");
        let kinds: Vec<&str> = input
            .iter()
            .map(|i| i.get("type").and_then(Value::as_str).unwrap_or("message"))
            .collect();
        assert_eq!(
            kinds,
            vec!["message", "function_call", "function_call_output"]
        );
        assert_eq!(input[1]["call_id"], "call_1");
        assert_eq!(input[1]["name"], "get_weather");
        // Arguments are a JSON *string* on this wire, not an object.
        assert!(input[1]["arguments"].is_string(), "{}", input[1]);
        assert_eq!(input[2]["call_id"], "call_1");
        assert_eq!(input[2]["output"], "18C");
    }

    /// The system turn is a message on chat, a top-level field on the other
    /// two — and must not survive as a `system` message where none is allowed.
    #[test]
    fn the_system_turn_is_hoisted_where_the_dialect_requires_it() {
        let items = items_from(
            ProviderKind::OpenAiChat,
            json!({
                "model": "m",
                "messages": [
                    {"role": "system", "content": "be terse"},
                    {"role": "user", "content": "hi"},
                ],
            }),
        );
        let anthropic = to_wire_request(
            ProviderKind::Anthropic,
            &config(ProviderKind::Anthropic),
            &items,
        )
        .expect("builds");
        assert_eq!(anthropic["system"], "be terse");
        assert_eq!(
            anthropic["messages"].as_array().unwrap().len(),
            1,
            "the system turn must not remain a message"
        );

        let responses = to_wire_request(
            ProviderKind::OpenAiResponses,
            &config(ProviderKind::OpenAiResponses),
            &items,
        )
        .expect("builds");
        assert_eq!(responses["instructions"], "be terse");
        assert_eq!(responses["input"].as_array().unwrap().len(), 1);
    }

    /// A signed thinking block is re-emitted verbatim; an unsigned one has no
    /// Anthropic wire form and is dropped rather than given a fabricated
    /// signature, which upstream would reject.
    #[test]
    fn anthropic_re_emits_signed_thinking_and_drops_unsigned() {
        let items = items_from(
            ProviderKind::Anthropic,
            json!({
                "model": "m", "max_tokens": 64,
                "messages": [
                    {"role": "user", "content": "think"},
                    {"role": "assistant", "content": [
                        {"type": "thinking", "thinking": "signed reasoning",
                         "signature": "sig-abc"},
                        {"type": "text", "text": "answer"},
                    ]},
                ],
            }),
        );
        let body = to_wire_request(
            ProviderKind::Anthropic,
            &config(ProviderKind::Anthropic),
            &items,
        )
        .expect("builds");
        let blocks = body["messages"][1]["content"].as_array().unwrap();
        assert_eq!(blocks[0]["type"], "thinking");
        assert_eq!(blocks[0]["signature"], "sig-abc");
        assert_eq!(blocks[0]["thinking"], "signed reasoning");
        assert_eq!(blocks[1]["text"], "answer");
    }

    /// A canonical request the crate rejects must fail here rather than reach a
    /// provider: an unresolved tool-result reference is the crate's own
    /// example, and every surface is supposed to 400 on it consistently.
    #[test]
    fn an_invalid_canonical_request_is_refused_before_any_call() {
        let mut items = items_from(
            ProviderKind::OpenAiChat,
            json!({"model":"m","messages":[{"role":"user","content":"hi"}]}),
        );
        items.messages.clear();
        let err = to_wire_request(
            ProviderKind::OpenAiChat,
            &config(ProviderKind::OpenAiChat),
            &items,
        )
        .expect_err("an empty request is invalid");
        assert!(matches!(err, BuildError::Invalid(_)), "{err:?}");
    }

    // -- SSE decoding -------------------------------------------------------

    /// A decoder fed one byte at a time must produce exactly what it produces
    /// fed all at once: a read boundary falls wherever the network puts it.
    #[test]
    fn the_sse_decoder_is_incremental_across_arbitrary_read_boundaries() {
        let body = "event: a\ndata: {\"x\":1}\n\ndata: hello\n\n";
        let mut whole = Vec::new();
        let mut d = SseDecoder::new();
        d.feed(body.as_bytes(), &mut whole);
        d.finish(&mut whole);

        for split in 0..body.len() {
            let mut parts = Vec::new();
            let mut d = SseDecoder::new();
            d.feed(&body.as_bytes()[..split], &mut parts);
            d.feed(&body.as_bytes()[split..], &mut parts);
            d.finish(&mut parts);
            assert_eq!(parts, whole, "split at byte {split} diverged");
        }
        assert_eq!(whole.len(), 2);
        assert_eq!(whole[0].event.as_deref(), Some("a"));
        assert_eq!(whole[0].data, "{\"x\":1}");
        assert_eq!(whole[1].event, None);
        assert_eq!(whole[1].data, "hello");
    }

    /// Only one leading space is stripped from a `data:` value — trimming would
    /// corrupt content that legitimately begins with whitespace.
    #[test]
    fn a_data_value_keeps_whitespace_beyond_the_first_space() {
        let mut out = Vec::new();
        let mut d = SseDecoder::new();
        d.feed(b"data:  two spaces\n\n", &mut out);
        assert_eq!(out[0].data, " two spaces");
    }

    /// Multiple `data:` lines in one frame join with newlines, and the newline
    /// that terminated the last line is not part of the value.
    #[test]
    fn multi_line_data_joins_and_drops_the_trailing_newline() {
        let mut out = Vec::new();
        let mut d = SseDecoder::new();
        d.feed(b"data: line one\ndata: line two\n\n", &mut out);
        assert_eq!(out[0].data, "line one\nline two");
    }

    /// Comments are keep-alives and carry no frame of their own.
    #[test]
    fn comment_lines_are_ignored() {
        let mut out = Vec::new();
        let mut d = SseDecoder::new();
        d.feed(b": ping\n\ndata: real\n\n", &mut out);
        assert_eq!(out.len(), 1, "a comment must not dispatch a frame: {out:?}");
        assert_eq!(out[0].data, "real");
    }

    /// A CRLF stream leaves no carriage return on the value.
    #[test]
    fn crlf_line_endings_do_not_leak_a_carriage_return() {
        let mut out = Vec::new();
        let mut d = SseDecoder::new();
        d.feed(b"event: a\r\ndata: v\r\n\r\n", &mut out);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].event.as_deref(), Some("a"));
        assert_eq!(out[0].data, "v");
    }

    /// A stream that closes without the final blank line still yields its data.
    #[test]
    fn an_unterminated_final_frame_is_still_delivered() {
        let mut out = Vec::new();
        let mut d = SseDecoder::new();
        d.feed(b"data: {\"a\":1}\n", &mut out);
        assert!(out.is_empty(), "no blank line yet");
        d.finish(&mut out);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].data, "{\"a\":1}");
    }

    // -- Provider stream decoding -------------------------------------------

    /// OpenAI chat deltas: text accumulates into one block that opens on the
    /// first delta and closes at `finish_reason`.
    #[test]
    fn chat_deltas_assemble_into_one_text_block() {
        let chunks = decode_stream(
            ProviderKind::OpenAiChat,
            concat!(
                "data: {\"choices\":[{\"index\":0,\"delta\":{\"role\":\"assistant\"},",
                "\"finish_reason\":null}]}\n\n",
                "data: {\"choices\":[{\"index\":0,\"delta\":{\"content\":\"Hel\"},",
                "\"finish_reason\":null}]}\n\n",
                "data: {\"choices\":[{\"index\":0,\"delta\":{\"content\":\"lo\"},",
                "\"finish_reason\":null}]}\n\n",
                "data: {\"choices\":[{\"index\":0,\"delta\":{},\"finish_reason\":\"stop\"}]}\n\n",
                "data: {\"choices\":[],\"usage\":{\"prompt_tokens\":3,\"completion_tokens\":2}}\n\n",
                "data: [DONE]\n\n",
            ),
        );
        let text: String = chunks
            .iter()
            .filter_map(|c| match c {
                StreamChunk::TextDelta { text, .. } => Some(text.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(text, "Hello");
        // Exactly one block, opened once and closed once.
        let starts = chunks
            .iter()
            .filter(|c| matches!(c, StreamChunk::BlockStart { .. }))
            .count();
        let ends = chunks
            .iter()
            .filter(|c| matches!(c, StreamChunk::BlockEnd { .. }))
            .count();
        assert_eq!((starts, ends), (1, 1), "{chunks:?}");
        assert_eq!(
            chunks.last(),
            Some(&StreamChunk::Finish {
                reason: FinishReason::Stop
            })
        );
        let usage = chunks
            .iter()
            .find_map(|c| match c {
                StreamChunk::Usage { usage } => Some(usage.clone()),
                _ => None,
            })
            .expect("usage trailer present");
        assert_eq!(usage["inputTokens"], 3);
        assert_eq!(usage["outputTokens"], 2);
    }

    /// The role-only opening delta carries no content and must not open a
    /// block; an empty text block would appear in the recorded stream.
    #[test]
    fn a_role_only_delta_opens_no_block() {
        let chunks = decode_stream(
            ProviderKind::OpenAiChat,
            concat!(
                "data: {\"choices\":[{\"index\":0,\"delta\":{\"role\":\"assistant\"},",
                "\"finish_reason\":null}]}\n\n",
                "data: {\"choices\":[{\"index\":0,\"delta\":{\"content\":\"x\"},",
                "\"finish_reason\":\"stop\"}]}\n\n",
                "data: [DONE]\n\n",
            ),
        );
        let starts: Vec<_> = chunks
            .iter()
            .filter(|c| matches!(c, StreamChunk::BlockStart { .. }))
            .collect();
        assert_eq!(starts.len(), 1, "{chunks:?}");
        assert_eq!(
            starts[0],
            &StreamChunk::BlockStart {
                index: 0,
                block_type: BlockType::Text
            }
        );
    }

    /// A tool call whose later fragments omit `id` and `index` must stay in the
    /// block its first fragment opened rather than opening a new one per piece.
    #[test]
    fn tool_call_fragments_stay_in_one_block_without_an_id() {
        let chunks = decode_stream(
            ProviderKind::OpenAiChat,
            concat!(
                "data: {\"choices\":[{\"index\":0,\"delta\":{\"tool_calls\":[{\"index\":0,",
                "\"id\":\"call_1\",\"type\":\"function\",\"function\":{\"name\":\"get_weather\",",
                "\"arguments\":\"\"}}]},\"finish_reason\":null}]}\n\n",
                "data: {\"choices\":[{\"index\":0,\"delta\":{\"tool_calls\":[{\"index\":0,",
                "\"function\":{\"arguments\":\"{\\\"city\\\":\"}}]},\"finish_reason\":null}]}\n\n",
                "data: {\"choices\":[{\"index\":0,\"delta\":{\"tool_calls\":[{\"index\":0,",
                "\"function\":{\"arguments\":\"\\\"Paris\\\"}\"}}]},\"finish_reason\":null}]}\n\n",
                "data: {\"choices\":[{\"index\":0,\"delta\":{},\"finish_reason\":\"tool_calls\"}]}\n\n",
                "data: [DONE]\n\n",
            ),
        );
        let calls: Vec<_> = chunks
            .iter()
            .filter_map(|c| match c {
                StreamChunk::ToolCallDelta {
                    index,
                    id,
                    name,
                    arguments_delta,
                } => Some((*index, id.clone(), name.clone(), arguments_delta.clone())),
                _ => None,
            })
            .collect();
        assert_eq!(calls.len(), 3, "{calls:?}");
        // One block index throughout, and the name rides only the first delta.
        assert!(calls.iter().all(|(i, ..)| *i == 0), "{calls:?}");
        assert_eq!(calls[0].2.as_deref(), Some("get_weather"));
        assert!(calls[1].2.is_none() && calls[2].2.is_none());
        let args: String = calls.iter().map(|(_, _, _, a)| a.as_str()).collect();
        assert_eq!(args, "{\"city\":\"Paris\"}");
        assert_eq!(
            chunks.last(),
            Some(&StreamChunk::Finish {
                reason: FinishReason::ToolCalls
            })
        );
    }

    /// `length` is a truncation, so it must map to `MaxTokens` rather than
    /// `Stop`: the FSM makes a turn's ending sticky on it, and a mis-mapped
    /// truncation would report a cut-off turn as a complete one.
    #[test]
    fn a_truncated_chat_response_reports_max_tokens() {
        for (wire, expect) in [
            ("length", FinishReason::MaxTokens),
            ("stop", FinishReason::Stop),
            ("tool_calls", FinishReason::ToolCalls),
        ] {
            let chunks = decode_stream(
                ProviderKind::OpenAiChat,
                &format!(
                    "data: {{\"choices\":[{{\"index\":0,\"delta\":{{\"content\":\"x\"}},\
                     \"finish_reason\":\"{wire}\"}}]}}\n\ndata: [DONE]\n\n"
                ),
            );
            assert_eq!(
                chunks.last(),
                Some(&StreamChunk::Finish {
                    reason: expect.clone()
                }),
                "wire reason {wire}"
            );
        }
    }

    /// A frame that is not JSON (a vendor keep-alive) is skipped rather than
    /// failing the stream.
    #[test]
    fn a_non_json_frame_is_skipped() {
        let chunks = decode_stream(
            ProviderKind::OpenAiChat,
            "data: {\"type\":\"ping\"}\n\ndata: not json at all\n\ndata: [DONE]\n\n",
        );
        assert!(chunks.is_empty(), "{chunks:?}");
    }

    /// Anthropic's blocks are explicit, so indices come from the wire rather
    /// than being invented — and the sealed signature survives to the block.
    #[test]
    fn anthropic_blocks_use_the_wire_index() {
        let chunks = decode_stream(
            ProviderKind::Anthropic,
            concat!(
                "event: message_start\ndata: {\"type\":\"message_start\",\"message\":",
                "{\"usage\":{\"input_tokens\":7}}}\n\n",
                "event: content_block_start\ndata: {\"type\":\"content_block_start\",",
                "\"index\":0,\"content_block\":{\"type\":\"thinking\",\"thinking\":\"\"}}\n\n",
                "event: content_block_delta\ndata: {\"type\":\"content_block_delta\",",
                "\"index\":0,\"delta\":{\"type\":\"thinking_delta\",\"thinking\":\"hmm\"}}\n\n",
                "event: content_block_delta\ndata: {\"type\":\"content_block_delta\",",
                "\"index\":0,\"delta\":{\"type\":\"signature_delta\",\"signature\":\"sig\"}}\n\n",
                "event: content_block_stop\ndata: {\"type\":\"content_block_stop\",\"index\":0}\n\n",
                "event: content_block_start\ndata: {\"type\":\"content_block_start\",",
                "\"index\":1,\"content_block\":{\"type\":\"text\",\"text\":\"\"}}\n\n",
                "event: content_block_delta\ndata: {\"type\":\"content_block_delta\",",
                "\"index\":1,\"delta\":{\"type\":\"text_delta\",\"text\":\"hi\"}}\n\n",
                "event: content_block_stop\ndata: {\"type\":\"content_block_stop\",\"index\":1}\n\n",
                "event: message_delta\ndata: {\"type\":\"message_delta\",",
                "\"delta\":{\"stop_reason\":\"end_turn\"},\"usage\":{\"output_tokens\":5}}\n\n",
                "event: message_stop\ndata: {\"type\":\"message_stop\"}\n\n",
            ),
        );
        // Reasoning opened at 0, text at 1 — the wire's own numbering.
        assert_eq!(
            chunks[0],
            StreamChunk::BlockStart {
                index: 0,
                block_type: BlockType::Reasoning
            }
        );
        assert!(chunks.contains(&StreamChunk::BlockEnd {
            index: 0,
            block: json!({"type":"reasoning","text":""}),
        }));
        assert!(chunks.contains(&StreamChunk::BlockStart {
            index: 1,
            block_type: BlockType::Text
        }));
        assert!(chunks.contains(&StreamChunk::TextDelta {
            index: 1,
            text: "hi".into()
        }));
        // The input count from `message_start` is folded into the trailing
        // usage, which on this surface carries output only.
        let usage = chunks
            .iter()
            .find_map(|c| match c {
                StreamChunk::Usage { usage } => Some(usage.clone()),
                _ => None,
            })
            .expect("usage present");
        assert_eq!(usage["inputTokens"], 7);
        assert_eq!(usage["outputTokens"], 5);
        assert_eq!(
            chunks.last(),
            Some(&StreamChunk::Finish {
                reason: FinishReason::Stop
            })
        );
    }

    /// Anthropic's `input_tokens` excludes cached tokens while the other two
    /// surfaces include them. Normalizing is what makes a recorded turn's cost
    /// comparable across providers.
    #[test]
    fn anthropic_usage_is_normalized_to_include_the_cache_classes() {
        let chunks = decode_stream(
            ProviderKind::Anthropic,
            concat!(
                "event: content_block_start\ndata: {\"type\":\"content_block_start\",",
                "\"index\":0,\"content_block\":{\"type\":\"text\",\"text\":\"\"}}\n\n",
                "event: message_delta\ndata: {\"type\":\"message_delta\",",
                "\"delta\":{\"stop_reason\":\"end_turn\"},\"usage\":",
                "{\"input_tokens\":10,\"cache_read_input_tokens\":90,",
                "\"cache_creation_input_tokens\":5,\"output_tokens\":3}}\n\n",
                "event: message_stop\ndata: {\"type\":\"message_stop\"}\n\n",
            ),
        );
        let usage = chunks
            .iter()
            .find_map(|c| match c {
                StreamChunk::Usage { usage } => Some(usage.clone()),
                _ => None,
            })
            .expect("usage present");
        // fresh 10 + cache read 90 + cache write 5
        assert_eq!(usage["inputTokens"], 105);
        assert_eq!(usage["outputTokens"], 3);
    }

    /// An Anthropic error event ends the stream with a structured failure
    /// rather than a `Stop`, so a failed call cannot replay as a success.
    #[test]
    fn an_anthropic_error_event_ends_with_a_structured_failure() {
        let chunks = decode_stream(
            ProviderKind::Anthropic,
            concat!(
                "event: content_block_start\ndata: {\"type\":\"content_block_start\",",
                "\"index\":0,\"content_block\":{\"type\":\"text\",\"text\":\"\"}}\n\n",
                "event: error\ndata: {\"type\":\"error\",\"error\":{\"type\":\"overloaded_error\",",
                "\"message\":\"overloaded\"}}\n\n",
            ),
        );
        match chunks.last() {
            Some(StreamChunk::Finish {
                reason: FinishReason::Error { message, code },
            }) => {
                assert_eq!(message, "overloaded");
                assert_eq!(code, "OVERLOADED_ERROR");
            }
            other => panic!("expected a structured error finish, got {other:?}"),
        }
        // The open block was closed rather than left dangling.
        assert!(
            chunks
                .iter()
                .any(|c| matches!(c, StreamChunk::BlockEnd { index: 0, .. })),
            "{chunks:?}"
        );
    }

    /// Responses carries tool calls as their own items and its terminal event
    /// must map back to `tool-calls` so the FSM opens another step.
    #[test]
    fn responses_tool_calls_and_usage_decode() {
        let chunks = decode_stream(
            ProviderKind::OpenAiResponses,
            concat!(
                "event: response.created\ndata: {\"type\":\"response.created\",\"response\":",
                "{\"id\":\"resp_1\"}}\n\n",
                "event: response.output_item.added\ndata: {\"type\":\"response.output_item.added\",",
                "\"item\":{\"type\":\"function_call\",\"call_id\":\"call_9\",\"name\":\"lookup\"}}\n\n",
                "event: response.function_call_arguments.delta\ndata: {\"type\":",
                "\"response.function_call_arguments.delta\",\"item_id\":\"call_9\",",
                "\"delta\":\"{\\\"q\\\":1}\"}\n\n",
                "event: response.completed\ndata: {\"type\":\"response.completed\",\"response\":",
                "{\"status\":\"completed\",\"usage\":{\"input_tokens\":4,\"output_tokens\":6}}}\n\n",
            ),
        );
        let calls: Vec<_> = chunks
            .iter()
            .filter_map(|c| match c {
                StreamChunk::ToolCallDelta {
                    index,
                    id,
                    name,
                    arguments_delta,
                } => Some((*index, id.clone(), name.clone(), arguments_delta.clone())),
                _ => None,
            })
            .collect();
        assert_eq!(calls.len(), 2, "{calls:?}");
        assert_eq!(calls[0].1, "call_9");
        assert_eq!(calls[0].2.as_deref(), Some("lookup"));
        assert_eq!(calls[1].3, "{\"q\":1}");
        assert_eq!(calls[1].0, calls[0].0, "same block as its opening item");
        assert_eq!(
            chunks.last(),
            Some(&StreamChunk::Finish {
                reason: FinishReason::ToolCalls
            }),
            "a completed response that emitted a call is a tool-calls turn"
        );
        let usage = chunks
            .iter()
            .find_map(|c| match c {
                StreamChunk::Usage { usage } => Some(usage.clone()),
                _ => None,
            })
            .expect("usage present");
        assert_eq!(usage["inputTokens"], 4);
        assert_eq!(usage["outputTokens"], 6);
    }

    /// `incomplete` means truncated on this surface, so it maps to `MaxTokens`.
    #[test]
    fn an_incomplete_responses_turn_reports_max_tokens() {
        let chunks = decode_stream(
            ProviderKind::OpenAiResponses,
            concat!(
                "event: response.output_text.delta\ndata: {\"type\":\"response.output_text.delta\",",
                "\"delta\":\"partial\"}\n\n",
                "event: response.incomplete\ndata: {\"type\":\"response.incomplete\",\"response\":",
                "{\"status\":\"incomplete\",\"incomplete_details\":",
                "{\"reason\":\"max_output_tokens\"}}}\n\n",
            ),
        );
        assert_eq!(
            chunks.last(),
            Some(&StreamChunk::Finish {
                reason: FinishReason::MaxTokens
            })
        );
    }

    /// An Anthropic backend fronted by a chat-completions surface streams
    /// reasoning as a nested `thinking` object rather than a
    /// `reasoning_content` string. Reading only the string form would drop
    /// every reasoning token — invisible in the visible text, and wrong in the
    /// log.
    ///
    /// The body below is a verbatim capture from a live gateway.
    #[test]
    fn a_nested_thinking_delta_is_read_as_reasoning() {
        let chunks = decode_stream(
            ProviderKind::OpenAiChat,
            concat!(
                "data: {\"choices\":[{\"delta\":{\"role\":\"assistant\"},",
                "\"finish_reason\":null,\"index\":0}]}\n\n",
                "data: {\"choices\":[{\"delta\":{\"thinking\":{\"block_index\":0,",
                "\"kind\":\"thinking\",\"text\":\" let me\"}},\"finish_reason\":null,",
                "\"index\":0}]}\n\n",
                "data: {\"choices\":[{\"delta\":{\"thinking\":{\"block_index\":0,",
                "\"kind\":\"thinking\",\"text\":\" think\"}},\"finish_reason\":null,",
                "\"index\":0}]}\n\n",
                "data: {\"choices\":[{\"delta\":{\"content\":\"PONG\"},\"finish_reason\":",
                "\"stop\",\"index\":0}]}\n\n",
                "data: {\"choices\":[],\"usage\":{\"prompt_tokens\":35,",
                "\"completion_tokens\":36}}\n\n",
                "data: [DONE]\n\n",
            ),
        );
        let reasoning: String = chunks
            .iter()
            .filter_map(|c| match c {
                StreamChunk::ReasoningDelta { text, .. } => Some(text.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(reasoning, " let me think", "{chunks:?}");
        // Reasoning is its own block, distinct from the text block.
        let starts: Vec<_> = chunks
            .iter()
            .filter_map(|c| match c {
                StreamChunk::BlockStart { index, block_type } => Some((*index, *block_type)),
                _ => None,
            })
            .collect();
        assert_eq!(
            starts,
            vec![(0, BlockType::Reasoning), (1, BlockType::Text)],
            "{chunks:?}"
        );
        // The text and the finish reason share a delta; the text still lands in
        // its own block, and the stream still ends with the finish.
        let text: String = chunks
            .iter()
            .filter_map(|c| match c {
                StreamChunk::TextDelta { text, .. } => Some(text.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(text, "PONG");
        assert!(
            chunks.last().is_some_and(StreamChunk::is_finish),
            "{chunks:?}"
        );
        // The usage trailer after the finish is still kept.
        assert!(
            chunks
                .iter()
                .any(|c| matches!(c, StreamChunk::Usage { .. })),
            "{chunks:?}"
        );
    }

    /// The same delta shape must not be confused with a text delta: a
    /// `thinking` object with a `text` field is reasoning, not content.
    #[test]
    fn a_thinking_object_is_never_treated_as_visible_text() {
        let chunks = decode_stream(
            ProviderKind::OpenAiChat,
            concat!(
                "data: {\"choices\":[{\"delta\":{\"thinking\":{\"block_index\":0,",
                "\"kind\":\"thinking\",\"text\":\"secret\"}},\"finish_reason\":\"stop\"}]}\n\n",
                "data: [DONE]\n\n",
            ),
        );
        assert!(
            !chunks
                .iter()
                .any(|c| matches!(c, StreamChunk::TextDelta { .. })),
            "reasoning leaked into the visible text: {chunks:?}"
        );
    }

    /// **Round trip through the crate's own framers.** The crate renders
    /// canonical chunks *outward* to each dialect's SSE; feeding that output
    /// back through this module's decoder must recover chunks that agree on
    /// the text, the tool call, and the finish reason. This is a stronger
    /// check than a hand-written fixture, because the producer is the same
    /// code a real gateway uses.
    #[test]
    fn a_round_trip_through_the_crates_framers_recovers_the_text() {
        use llm_dialect::canonical::CanonChunk;
        use llm_dialect::dialect::openai_chat::stream::OpenAiFramer;

        let mut framer = OpenAiFramer::new("cmpl-1".into(), "test-model".into(), 0, true);
        let mut sse = String::new();
        for chunk in [
            CanonChunk {
                delta_text: "Hello".into(),
                ..Default::default()
            },
            CanonChunk {
                delta_text: " world".into(),
                ..Default::default()
            },
            CanonChunk {
                finish_reason: Some("stop".into()),
                ..Default::default()
            },
        ] {
            for segment in framer.frame_chunk(&chunk) {
                sse.push_str(&segment);
            }
        }
        for segment in framer.finish() {
            sse.push_str(&segment);
        }

        let decoded = decode_stream(ProviderKind::OpenAiChat, &sse);
        let text: String = decoded
            .iter()
            .filter_map(|c| match c {
                StreamChunk::TextDelta { text, .. } => Some(text.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(text, "Hello world", "SSE was: {sse}");
        assert_eq!(
            decoded.last(),
            Some(&StreamChunk::Finish {
                reason: FinishReason::Stop
            })
        );
    }

    /// The same round trip for Anthropic, where the crate emits explicit
    /// blocks — so the recovered indices must match the framer's own.
    #[test]
    fn a_round_trip_through_the_anthropic_framer_recovers_the_text() {
        use llm_dialect::canonical::CanonChunk;
        use llm_dialect::dialect::anthropic::stream::{
            StreamState, chunk_to_sse_events, finalize_stream,
        };

        let mut state = StreamState::new();
        let mut sse = String::new();
        for chunk in [
            CanonChunk {
                delta_text: "Hi".into(),
                ..Default::default()
            },
            CanonChunk {
                delta_text: " there".into(),
                ..Default::default()
            },
        ] {
            for (event, data) in chunk_to_sse_events(&chunk, "test-model", &mut state, "msg_1") {
                sse.push_str(&format!("event: {event}\ndata: {data}\n\n"));
            }
        }
        for (event, data) in finalize_stream(&mut state) {
            sse.push_str(&format!("event: {event}\ndata: {data}\n\n"));
        }

        let decoded = decode_stream(ProviderKind::Anthropic, &sse);
        let text: String = decoded
            .iter()
            .filter_map(|c| match c {
                StreamChunk::TextDelta { text, .. } => Some(text.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(text, "Hi there", "SSE was: {sse}");
        // Frames must be balanced: every block opened is closed.
        let starts = decoded
            .iter()
            .filter(|c| matches!(c, StreamChunk::BlockStart { .. }))
            .count();
        let ends = decoded
            .iter()
            .filter(|c| matches!(c, StreamChunk::BlockEnd { .. }))
            .count();
        assert_eq!((starts, ends), (1, 1), "{decoded:?}");
        assert_eq!(
            decoded.last(),
            Some(&StreamChunk::Finish {
                reason: FinishReason::Stop
            })
        );
    }
}
